### ISSUE TITLE
Define Job Description Language (JDL)

### ISSUE THREAD

**Issue by jasonprado** [openmarketplaceengine/openmarketplaceengine#35]
Design doc in progress: https://docs.google.com/document/d/1WXM4hkdjnQj-YzdeLk2y2qycarhWDAM7Kz4_7nVDecA/edit#

**Comment by vlkolmakov** [comment]
> Not clear how to handle changes once a trip has begun.

When a Client submits a job to the OME, the server issues job's GUID and send it back to the client for further updates/queries.

Update Example:
```yaml
update: 
  job: 123e4567-e89b-12d3-a456-426614174000
  current_action: GO_TO_LOCATION
    location:
      latitude: 40.7068
      longitude: 73.9236
  update_action: VEHICLE_FAILURE/ROAD_ACCIDENT/PASSENGER_REQUIRES_MEDICAL_HELP
    # update_action attributes
```
